language: ruby
install: ./script/bootstrap
script: ./script/cibuild
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
notifications:
  email: false
cache:
  directories:
    - vendor/bundle
    - node_modules
    - bower_components
